---
- hosts: mark
  tasks:

    - name: Set a hostname
      ansible.builtin.hostname:
        name: "mark08"

### INSTALAR PACOTES BASICOS INICIAIS ###
    - name: apt-get update
      apt:
        update_cache: yes

  ### INSTALAR PACOTES BASICOS INICIAIS ###
    - name: Install a list of packages
      apt:
        pkg:
        - ntp
        - htop
        - vim
        - apt-transport-https
        - ca-certificates
        - curl
        - net-tools
        - lvm2
        - bash-completion

  ### CRIAR USUÁRIO ###
    - name: Add the user Stark
      user:
        name: stark
        comment: stark
        uid: 1414
        shell: /bin/bash
        group: sudo
        append: yes

  ### DESLIGAR SWAP ###
    - name: Configure timezone
      shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab && swapoff -a

  ### CONFIGURE CGOUP ###
    - name: Configure timezone
      shell: echo "$(head -n1 /boot/firmware/cmdline.txt) cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1" | sudo tee /boot/firmware/cmdline.txt

  ### CONFIGURE NTP ###
    - name: Configure timezone
      shell: timedatectl set-timezone America/Sao_Paulo

    - name: Restart ntp
      shell: service ntp restart

  ### UPGRADE DO SO ###
    - name: Update all packages to the latest version
      apt:
        upgrade: dist

  ### DEFINE CRIA IP E DNS ###
    - name: Insert/Update IP/GW/DNS
      blockinfile:
        create: yes
        path: /etc/netplan/01-netcfg.yaml
        block: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              eth0:
                dhcp4: no
                addresses:
                  - 192.168.0.8/24
                gateway4: 192.168.0.1
                nameservers:
                  addresses: [192.168.0.1, 8.8.8.8]

  ### DESLIGAR DHCP ###
    - name: Limpar arquivo de configuração DHCP
      shell: sed '/^$/d' /etc/netplan/50-cloud-init.yaml

  ### DEFINE IP STATIC ###
    - name: define ip static
      blockinfile:
        block: "network: {config: disabled}"
        path: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
        create: yes

  ### INSTALAR PACOTES BASICOS INICIAIS ###
    - name: Install containerd
      apt:
        name: containerd
        update_cache: yes

  ### CONFIGURE Criar diretório containerd ###
    - name: create directory containerd
      shell: mkdir -p /etc/containerd

  ### CONFIGURE containerd ###
    - name: Configure containerd - config.toml
      shell: containerd config default > /etc/containerd/config.toml

 
  ### CONFIGURE  containerd###
    - name: Insert/Update containerd.conf
      blockinfile:
        create: yes
        path: /etc/modules-load.d/containerd.conf
        block: |
         overlay
         br_netfilter

    - name: Aplicando modificacoes overlay e br_netfilter
      shell: modprobe overlay && modprobe br_netfilter


### CONFIGURE  sysctl e modulos ###
    - name: Insert/Update 99-kubernetes-cri.conf
      blockinfile:
        create: yes
        path: /etc/sysctl.d/99-kubernetes-cri.conf
        block: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1

    - name: Aplicando modificacoes sysctl
      shell: sysctl --system

    - name: Reiniciando serviço containerd
      shell: systemctl restart containerd

    - name: Insert/Update k8s.conf
      blockinfile:
        create: yes
        path: /etc/modules-load.d/k8s.conf
        block: |
          ip_vs
          ip_vs_rr
          ip_vs_sh
          ip_vs_wrr
          nf_conntrack_ipv4  


  ### CONFIGURE Kubernetes repo ###
    - name: Add an Apt signing key kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc//apt-key.gpg.asc
        state: present

    - apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes-xenial


  ### INSTALAR PACOTES KUBERNETES ###
    - name: Install a list of packages
      apt:
        pkg:
        - kubeadm=1.21.4-00
        - kubelet=1.21.4-00
        - kubectl=1.21.4-00
